test_attributs_accessoire (__main__.TestAccessoire) ... ERROR
test_constructeur (__main__.TestAccessoire) ... FAIL
test_score_viral_bijou (__main__.TestAccessoire) ... ERROR
test_score_viral_chapeau (__main__.TestAccessoire) ... ERROR
test_score_viral_chaussures (__main__.TestAccessoire) ... ERROR
test_score_viral_vetement (__main__.TestAccessoire) ... ERROR
test_str (__main__.TestAccessoire) ... ERROR
test_add (__main__.TestAnimal) ... ERROR
test_calcul_meilleur_animal (__main__.TestAnimal) ... ERROR
test_crier_abstraite (__main__.TestAnimal) ... FAIL
test_iadd (__main__.TestAnimal) ... ERROR
test_iadd_chaussures (__main__.TestAnimal) ... ERROR
test_score_viral_animal (__main__.TestAnimal) ... ERROR
test_attributs_compte (__main__.TestCompteTikTok) ... ERROR
test_constructeur_compte (__main__.TestCompteTikTok) ... FAIL
test_iadd_compte (__main__.TestCompteTikTok) ... ERROR
test_len_compte (__main__.TestCompteTikTok) ... ERROR
test_tiktoks_plus_populaires (__main__.TestCompteTikTok) ... ERROR
test_vues_compte (__main__.TestCompteTikTok) ... ERROR
test_score_viral_abstraite (__main__.TestElementViral) ... FAIL
test_attributs_filtre (__main__.TestFiltre) ... FAIL
test_score_viral_filtre (__main__.TestFiltre) ... FAIL
test_main (__main__.TestMain) ... ERROR
test_attributs_chat (__main__.TestMammifere) ... ERROR
test_constructeur_chat (__main__.TestMammifere) ... FAIL
test_crier_chat (__main__.TestMammifere) ... ERROR
test_str_mammifere (__main__.TestMammifere) ... ERROR
test_attributs (__main__.TestMusique) ... FAIL
test_score_viral (__main__.TestMusique) ... FAIL
test_attributs_cockatiel (__main__.TestOiseau) ... ERROR
test_constructeur_cockatiel (__main__.TestOiseau) ... FAIL
test_crier_oiseau_chant (__main__.TestOiseau) ... ERROR
test_crier_oiseau_sans_chant (__main__.TestOiseau) ... ERROR
test_str_chant (__main__.TestOiseau) ... ERROR
test_str_sans_chant (__main__.TestOiseau) ... ERROR
test_attributs_serpent (__main__.TestReptile) ... ERROR
test_constructeur_serpent (__main__.TestReptile) ... FAIL
test_crier_serpent (__main__.TestReptile) ... ERROR
test_str_diurne (__main__.TestReptile) ... ERROR
test_str_nocturne (__main__.TestReptile) ... ERROR
test_str_serpent_non_venimeux (__main__.TestReptile) ... ERROR
test_str_serpent_venimeux (__main__.TestReptile) ... ERROR
test_ajouter_animal (__main__.TestTikTok) ... ERROR
test_attributs_tiktok (__main__.TestTikTok) ... ERROR
test_constructeur_tiktok (__main__.TestTikTok) ... FAIL
test_lt (__main__.TestTikTok) ... ERROR
test_str_tiktok (__main__.TestTikTok) ... ERROR
test_vues_tiktok (__main__.TestTikTok) ... ERROR

======================================================================
ERROR: test_attributs_accessoire (__main__.TestAccessoire)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/2022A_TP5/2022A_TP5/test_assignment.py", line 59, in test_attributs_accessoire
    accessoire = Accessoire("Boots with the fur", 10, TypeAccessoire.CHAUSSURES)
TypeError: Accessoire() takes no arguments

======================================================================
ERROR: test_score_viral_bijou (__main__.TestAccessoire)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/2022A_TP5/2022A_TP5/test_assignment.py", line 82, in test_score_viral_bijou
    accessoire = Accessoire("Collier de macaroni", 40, TypeAccessoire.BIJOU)
TypeError: Accessoire() takes no arguments

======================================================================
ERROR: test_score_viral_chapeau (__main__.TestAccessoire)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/2022A_TP5/2022A_TP5/test_assignment.py", line 74, in test_score_viral_chapeau
    accessoire = Accessoire("Haut-de-forme", 15, TypeAccessoire.CHAPEAU)
TypeError: Accessoire() takes no arguments

======================================================================
ERROR: test_score_viral_chaussures (__main__.TestAccessoire)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/2022A_TP5/2022A_TP5/test_assignment.py", line 78, in test_score_viral_chaussures
    accessoire = Accessoire("Bottes de pluie", 12, TypeAccessoire.CHAUSSURES)
TypeError: Accessoire() takes no arguments

======================================================================
ERROR: test_score_viral_vetement (__main__.TestAccessoire)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/2022A_TP5/2022A_TP5/test_assignment.py", line 86, in test_score_viral_vetement
    accessoire = Accessoire("Costume d'abeille", 40, TypeAccessoire.VETEMENT)
TypeError: Accessoire() takes no arguments

======================================================================
ERROR: test_str (__main__.TestAccessoire)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/2022A_TP5/2022A_TP5/test_assignment.py", line 67, in test_str
    accessoire = Accessoire("Couronne", 20, TypeAccessoire.BIJOU)
TypeError: Accessoire() takes no arguments

======================================================================
ERROR: test_add (__main__.TestAnimal)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/2022A_TP5/2022A_TP5/test_assignment.py", line 92, in test_add
    accessoire = Accessoire("Costume d'abeille", 40, TypeAccessoire.VETEMENT)
TypeError: Accessoire() takes no arguments

======================================================================
ERROR: test_calcul_meilleur_animal (__main__.TestAnimal)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/2022A_TP5/2022A_TP5/test_assignment.py", line 134, in test_calcul_meilleur_animal
    accessoire1 = Accessoire("Costume d'abeille", 40, TypeAccessoire.VETEMENT)
TypeError: Accessoire() takes no arguments

======================================================================
ERROR: test_iadd (__main__.TestAnimal)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/2022A_TP5/2022A_TP5/test_assignment.py", line 102, in test_iadd
    accessoire = Accessoire("Costume d'abeille", 40, TypeAccessoire.VETEMENT)
TypeError: Accessoire() takes no arguments

======================================================================
ERROR: test_iadd_chaussures (__main__.TestAnimal)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/2022A_TP5/2022A_TP5/test_assignment.py", line 111, in test_iadd_chaussures
    accessoire = Accessoire("Bottes de pluie", 10, TypeAccessoire.CHAUSSURES)
TypeError: Accessoire() takes no arguments

======================================================================
ERROR: test_score_viral_animal (__main__.TestAnimal)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/2022A_TP5/2022A_TP5/test_assignment.py", line 124, in test_score_viral_animal
    terreur = Chat("Milo le terrible", LongueurPoils.COURTS, "Noir et blanc")
TypeError: Chat() takes no arguments

======================================================================
ERROR: test_attributs_compte (__main__.TestCompteTikTok)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/2022A_TP5/2022A_TP5/test_assignment.py", line 338, in test_attributs_compte
    compte_tiktok = CompteTikTok("NosAmisLesAnimaux")
TypeError: CompteTikTok() takes no arguments

======================================================================
ERROR: test_iadd_compte (__main__.TestCompteTikTok)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/2022A_TP5/2022A_TP5/test_assignment.py", line 352, in test_iadd_compte
    compte_tiktok = CompteTikTok("NosAmisLesAnimaux")
TypeError: CompteTikTok() takes no arguments

======================================================================
ERROR: test_len_compte (__main__.TestCompteTikTok)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/2022A_TP5/2022A_TP5/test_assignment.py", line 346, in test_len_compte
    compte_tiktok = CompteTikTok("NosAmisLesAnimaux")
TypeError: CompteTikTok() takes no arguments

======================================================================
ERROR: test_tiktoks_plus_populaires (__main__.TestCompteTikTok)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.10/unittest/mock.py", line 1369, in patched
    return func(*newargs, **newkeywargs)
  File "/home/runner/work/2022A_TP5/2022A_TP5/test_assignment.py", line 375, in test_tiktoks_plus_populaires
    compte_tiktok = CompteTikTok("NosAmisLesAnimaux")
TypeError: CompteTikTok() takes no arguments

======================================================================
ERROR: test_vues_compte (__main__.TestCompteTikTok)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/2022A_TP5/2022A_TP5/test_assignment.py", line 361, in test_vues_compte
    compte_tiktok = CompteTikTok("NosAmisLesAnimaux")
TypeError: CompteTikTok() takes no arguments

======================================================================
ERROR: test_main (__main__.TestMain)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/2022A_TP5/2022A_TP5/test_assignment.py", line 394, in test_main
    compte_tiktok = main()
  File "/home/runner/work/2022A_TP5/2022A_TP5/main.py", line 83, in main
    print("Le compte TikTok", compte.identifiant, "contient", nombre_tiktok_compte, "TikToks")
AttributeError: 'ellipsis' object has no attribute 'identifiant'

======================================================================
ERROR: test_attributs_chat (__main__.TestMammifere)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/2022A_TP5/2022A_TP5/test_assignment.py", line 163, in test_attributs_chat
    terreur = Chat("Milo le terrible", LongueurPoils.COURTS, "Noir et blanc")
TypeError: Chat() takes no arguments

======================================================================
ERROR: test_crier_chat (__main__.TestMammifere)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/2022A_TP5/2022A_TP5/test_assignment.py", line 171, in test_crier_chat
    terreur = Chat("Milo le terrible", LongueurPoils.COURTS, "Noir et blanc")
TypeError: Chat() takes no arguments

======================================================================
ERROR: test_str_mammifere (__main__.TestMammifere)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/2022A_TP5/2022A_TP5/test_assignment.py", line 157, in test_str_mammifere
    terreur = Chat("Milo le terrible", LongueurPoils.COURTS, "Noir et blanc")
TypeError: Chat() takes no arguments

======================================================================
ERROR: test_attributs_cockatiel (__main__.TestOiseau)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/2022A_TP5/2022A_TP5/test_assignment.py", line 183, in test_attributs_cockatiel
    kevin = Cockatiel("Kevin l'oiseau rare", 2)
TypeError: Cockatiel() takes no arguments

======================================================================
ERROR: test_crier_oiseau_chant (__main__.TestOiseau)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/2022A_TP5/2022A_TP5/test_assignment.py", line 203, in test_crier_oiseau_chant
    zazu = Cockatiel("Zazu", 2)
TypeError: Cockatiel() takes no arguments

======================================================================
ERROR: test_crier_oiseau_sans_chant (__main__.TestOiseau)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/2022A_TP5/2022A_TP5/test_assignment.py", line 209, in test_crier_oiseau_sans_chant
    kevin = Cockatiel("Kevin l'oiseau rare", 2)
TypeError: Cockatiel() takes no arguments

======================================================================
ERROR: test_str_chant (__main__.TestOiseau)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/2022A_TP5/2022A_TP5/test_assignment.py", line 189, in test_str_chant
    zazu = Cockatiel("Zazu", 2)
TypeError: Cockatiel() takes no arguments

======================================================================
ERROR: test_str_sans_chant (__main__.TestOiseau)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/2022A_TP5/2022A_TP5/test_assignment.py", line 195, in test_str_sans_chant
    kevin = Cockatiel("Kevin l'oiseau rare", 2)
TypeError: Cockatiel() takes no arguments

======================================================================
ERROR: test_attributs_serpent (__main__.TestReptile)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/2022A_TP5/2022A_TP5/test_assignment.py", line 225, in test_attributs_serpent
    snek = Serpent("Noodle", True, False)
TypeError: Serpent() takes no arguments

======================================================================
ERROR: test_crier_serpent (__main__.TestReptile)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/2022A_TP5/2022A_TP5/test_assignment.py", line 265, in test_crier_serpent
    snek = Serpent("Danger Noodle", True, True)
TypeError: Serpent() takes no arguments

======================================================================
ERROR: test_str_diurne (__main__.TestReptile)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/2022A_TP5/2022A_TP5/test_assignment.py", line 239, in test_str_diurne
    snek = Serpent("Noodle", False, False)
TypeError: Serpent() takes no arguments

======================================================================
ERROR: test_str_nocturne (__main__.TestReptile)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/2022A_TP5/2022A_TP5/test_assignment.py", line 233, in test_str_nocturne
    snek = Serpent("Noodle", True, False)
TypeError: Serpent() takes no arguments

======================================================================
ERROR: test_str_serpent_non_venimeux (__main__.TestReptile)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.10/unittest/mock.py", line 1369, in patched
    return func(*newargs, **newkeywargs)
  File "/home/runner/work/2022A_TP5/2022A_TP5/test_assignment.py", line 256, in test_str_serpent_non_venimeux
    snek = Serpent("Noodle", True, False)
TypeError: Serpent() takes no arguments

======================================================================
ERROR: test_str_serpent_venimeux (__main__.TestReptile)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.10/unittest/mock.py", line 1369, in patched
    return func(*newargs, **newkeywargs)
  File "/home/runner/work/2022A_TP5/2022A_TP5/test_assignment.py", line 246, in test_str_serpent_venimeux
    snek = Serpent("Danger Noodle", True, True)
TypeError: Serpent() takes no arguments

======================================================================
ERROR: test_ajouter_animal (__main__.TestTikTok)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/2022A_TP5/2022A_TP5/test_assignment.py", line 285, in test_ajouter_animal
    tiktok = TikTok("Milo essaye de manger le laptop d'un chargé de INF1007")
TypeError: TikTok() takes no arguments

======================================================================
ERROR: test_attributs_tiktok (__main__.TestTikTok)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/2022A_TP5/2022A_TP5/test_assignment.py", line 277, in test_attributs_tiktok
    tiktok = TikTok("Toe Beans")
TypeError: TikTok() takes no arguments

======================================================================
ERROR: test_lt (__main__.TestTikTok)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.10/unittest/mock.py", line 1369, in patched
    return func(*newargs, **newkeywargs)
  File "/home/runner/work/2022A_TP5/2022A_TP5/test_assignment.py", line 294, in test_lt
    tiktok1 = TikTok("TikTok cool")
TypeError: TikTok() takes no arguments

======================================================================
ERROR: test_str_tiktok (__main__.TestTikTok)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.10/unittest/mock.py", line 1369, in patched
    return func(*newargs, **newkeywargs)
  File "/home/runner/work/2022A_TP5/2022A_TP5/test_assignment.py", line 306, in test_str_tiktok
    tiktok = TikTok("Milo l'abeille essaye de manger le laptop d'un chargé de INF1007")
TypeError: TikTok() takes no arguments

======================================================================
ERROR: test_vues_tiktok (__main__.TestTikTok)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/2022A_TP5/2022A_TP5/test_assignment.py", line 316, in test_vues_tiktok
    tiktok = TikTok("La magie des MagicMock")
TypeError: TikTok() takes no arguments

======================================================================
FAIL: test_constructeur (__main__.TestAccessoire)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/2022A_TP5/2022A_TP5/test_assignment.py", line 54, in test_constructeur
    Accessoire("Boots with the fur", 10, TypeAccessoire.CHAUSSURES)
TypeError: Accessoire() takes no arguments

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/2022A_TP5/2022A_TP5/test_assignment.py", line 56, in test_constructeur
    self.fail("Le constructeur de Accessoire n'a pas été implanté correctement.")
AssertionError: Le constructeur de Accessoire n'a pas été implanté correctement.

======================================================================
FAIL: test_crier_abstraite (__main__.TestAnimal)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/2022A_TP5/2022A_TP5/test_assignment.py", line 120, in test_crier_abstraite
    self.assertTrue(issubclass(Animal, ABC), "La classe Animal n'est pas abstraite")
AssertionError: False is not true : La classe Animal n'est pas abstraite

======================================================================
FAIL: test_constructeur_compte (__main__.TestCompteTikTok)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/2022A_TP5/2022A_TP5/test_assignment.py", line 333, in test_constructeur_compte
    CompteTikTok("NosAmisLesAnimaux")
TypeError: CompteTikTok() takes no arguments

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/2022A_TP5/2022A_TP5/test_assignment.py", line 335, in test_constructeur_compte
    self.fail("Le constructeur de CompteTikTok n'a pas été implanté correctement.")
AssertionError: Le constructeur de CompteTikTok n'a pas été implanté correctement.

======================================================================
FAIL: test_score_viral_abstraite (__main__.TestElementViral)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/2022A_TP5/2022A_TP5/test_assignment.py", line 20, in test_score_viral_abstraite
    self.assertTrue(issubclass(ElementViral, ABC), "La classe ElementViral n'est pas abstraite.")
AssertionError: False is not true : La classe ElementViral n'est pas abstraite.

======================================================================
FAIL: test_attributs_filtre (__main__.TestFiltre)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/2022A_TP5/2022A_TP5/test_assignment.py", line 40, in test_attributs_filtre
    self.assertTrue(hasattr(filtre, 'nom'), "La classe Filtre n'a pas d'attribut public 'nom'.")
AssertionError: False is not true : La classe Filtre n'a pas d'attribut public 'nom'.

======================================================================
FAIL: test_score_viral_filtre (__main__.TestFiltre)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/2022A_TP5/2022A_TP5/test_assignment.py", line 47, in test_score_viral_filtre
    self.assertIsInstance(score_viral, int, msg="Filtre.score_viral doit être un int.")
AssertionError: None is not an instance of <class 'int'> : Filtre.score_viral doit être un int.

======================================================================
FAIL: test_constructeur_chat (__main__.TestMammifere)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/2022A_TP5/2022A_TP5/test_assignment.py", line 152, in test_constructeur_chat
    Chat("Milo le terrible", LongueurPoils.COURTS, "Noir et blanc")
TypeError: Chat() takes no arguments

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/2022A_TP5/2022A_TP5/test_assignment.py", line 154, in test_constructeur_chat
    self.fail("Le constructeur de Chat n'a pas été implanté correctement.")
AssertionError: Le constructeur de Chat n'a pas été implanté correctement.

======================================================================
FAIL: test_attributs (__main__.TestMusique)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/2022A_TP5/2022A_TP5/test_assignment.py", line 27, in test_attributs
    self.assertTrue(hasattr(musique, 'titre'), "La classe Musique n'a pas d'attribut public 'titre'.")
AssertionError: False is not true : La classe Musique n'a pas d'attribut public 'titre'.

======================================================================
FAIL: test_score_viral (__main__.TestMusique)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/2022A_TP5/2022A_TP5/test_assignment.py", line 33, in test_score_viral
    self.assertIsInstance(score_viral, int, msg="Musique.score_viral doit être un int.")
AssertionError: None is not an instance of <class 'int'> : Musique.score_viral doit être un int.

======================================================================
FAIL: test_constructeur_cockatiel (__main__.TestOiseau)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/2022A_TP5/2022A_TP5/test_assignment.py", line 178, in test_constructeur_cockatiel
    Cockatiel("Kevin l'oiseau rare", 2)
TypeError: Cockatiel() takes no arguments

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/2022A_TP5/2022A_TP5/test_assignment.py", line 180, in test_constructeur_cockatiel
    self.fail("Le constructeur de Cockatiel n'a pas été implanté correctement.")
AssertionError: Le constructeur de Cockatiel n'a pas été implanté correctement.

======================================================================
FAIL: test_constructeur_serpent (__main__.TestReptile)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/2022A_TP5/2022A_TP5/test_assignment.py", line 220, in test_constructeur_serpent
    Serpent("Danger Noodle", True, True)
TypeError: Serpent() takes no arguments

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/2022A_TP5/2022A_TP5/test_assignment.py", line 222, in test_constructeur_serpent
    self.fail("Le constructeur de Serpent n'a pas été implanté correctement.")
AssertionError: Le constructeur de Serpent n'a pas été implanté correctement.

======================================================================
FAIL: test_constructeur_tiktok (__main__.TestTikTok)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/2022A_TP5/2022A_TP5/test_assignment.py", line 272, in test_constructeur_tiktok
    TikTok("Toe Beans")
TypeError: TikTok() takes no arguments

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/2022A_TP5/2022A_TP5/test_assignment.py", line 274, in test_constructeur_tiktok
    self.fail("Le constructeur de TikTok n'a pas été implanté correctement.")
AssertionError: Le constructeur de TikTok n'a pas été implanté correctement.

----------------------------------------------------------------------
Ran 48 tests in 0.027s

FAILED (failures=12, errors=36)
